import { createHash } from "node:crypto";
import { stat } from "node:fs/promises";
import { basename } from "node:path";
import { MANIFEST_SCHEMA_URL, MANIFEST_VERSION, TASK_SCHEMA_VERSION, createId } from "../model/types.js";

export class ManifestGenerator {
  async createForFile(options) {
    const fileStats = await stat(options.filePath);
    const checksum = checksumBuffer(options.content);
    return this.create({
      ...options,
      fileSizeBytes: fileStats.size,
      checksum
    });
  }

  create(options) {
    const generatedAt = options.generatedAt || new Date().toISOString();
    const taskIds = options.taskIds || [];
    return {
      $schema: MANIFEST_SCHEMA_URL,
      manifest_version: MANIFEST_VERSION,
      dataset_id: options.datasetId || createId("ds", `${options.format || "dataset"}_${Date.now()}`),
      dataset_name: options.datasetName || `${options.format || "dataset"}-${generatedAt.slice(0, 10)}`,
      source: {
        schema_version: options.schemaVersion || TASK_SCHEMA_VERSION,
        profile: options.profile || "sharegpt",
        profile_version: options.profileVersion || "1.0.0",
        generator: options.generator || "vibe-archive-cli@0.1.0",
        generated_at: generatedAt,
        repository: options.repository
      },
      content: {
        record_count: options.recordCount || 0,
        task_ids: taskIds.slice(0, 1000),
        file_path: options.relativeFilePath || basename(options.filePath || "dataset.jsonl"),
        file_size_bytes: options.fileSizeBytes || Buffer.byteLength(options.content || ""),
        format: "jsonl",
        compression: "none",
        checksum: {
          algorithm: "sha256",
          value: options.checksum || checksumBuffer(options.content || "")
        }
      },
      pipeline: {
        stages: ["normalize", "transform", "export"],
        filter_config: {
          min_quality_score: options.minQualityScore,
          required_decision: Boolean(options.requiredDecision),
          allowed_domains: options.allowedDomains || [],
          exclude_languages: options.excludeLanguages || [],
          training_ready_only: Boolean(options.trainingReadyOnly)
        },
        post_process_config: {
          dedup_enabled: Boolean(options.dedupEnabled),
          dedup_method: "content_hash",
          max_tokens_per_sample: options.maxTokensPerSample || 4096,
          trim_strategy: "preserve_system_and_recent"
        }
      },
      quality: options.quality,
      provenance: {
        source_tasks_count: options.sourceTasksCount || options.recordCount || 0,
        rejected_tasks_count: options.rejectedTasksCount || 0,
        rejected_reasons: options.rejectedReasons || {},
        source_tools: options.sourceTools || {}
      },
      license: options.license,
      attribution: options.attribution || "Generated by Vibe Archive CLI",
      retention_policy: options.retentionPolicy || "keep_forever",
      data_classification: options.dataClassification || "internal"
    };
  }
}

export function checksumBuffer(content) {
  return createHash("sha256").update(content || "").digest("hex");
}
